const boss = [
  {
    id: 1,
    name: "탈킨",
    nameAbbreviation: "ㅌㅋ",
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
  },
  {
    id: 2,
    name: "펠리스",
    nameAbbreviation: "ㅍㄹㅅ",
    genTime: null,
    time: 3,
    mungCount: 0,
    memo: "",
  },
  {
    id: 3,
    name: "판나로드",
    nameAbbreviation: "ㅍㄴㄹㄷ",
    genTime: null,
    time: 5,
    mungCount: 0,
    memo: "",
  },
  {
    id: 4,
    name: "브래카",
    nameAbbreviation: "ㅂㄹㅋ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 5,
    name: "바실라",
    nameAbbreviation: "ㅂㅅㄹ",
    genTime: null,
    time: 4,
    mungCount: 0,
    memo: "",
  },
  {
    id: 6,
    name: "엔쿠라",
    nameAbbreviation: "ㅇㅋㄹ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 7,
    name: "체르투바",
    nameAbbreviation: "ㅊㄹㅌㅂ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 8,
    name: "마투라",
    nameAbbreviation: "ㅁㅌㄹ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 9,
    name: "트롬바",
    nameAbbreviation: "ㅌㄹㅂ",
    genTime: null,
    time: 7,
    mungCount: 0,
    memo: "",
  },
  {
    id: 10,
    name: "사르카",
    nameAbbreviation: "ㅅㄹㅋ",
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
  },
  {
    id: 11,
    name: "오크",
    nameAbbreviation: "ㅇㅋ",
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
  },
  {
    id: 12,
    name: "셀루",
    nameAbbreviation: "ㅅㄹ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 13,
    name: "발보",
    nameAbbreviation: "ㅂㅂ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 14,
    name: "티미니엘",
    nameAbbreviation: "ㅌㅁㄴㅇ",
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
  },
  {
    id: 15,
    name: "레피로",
    nameAbbreviation: "ㄹㅍㄹ",
    genTime: null,
    time: 7,
    mungCount: 0,
    memo: "",
  },
  {
    id: 16,
    name: "코룬",
    nameAbbreviation: "ㅋㄹ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 17,
    name: "켈소스",
    nameAbbreviation: "ㅋㅅㅅ",
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
  },
  {
    id: 18,
    name: "사반",
    nameAbbreviation: "ㅅㅂ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 19,
    name: "여왕개미",
    nameAbbreviation: "ㅇㅇㄱㅁ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 20,
    name: "탈라킨",
    nameAbbreviation: "ㅌㄹㅋ",
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
  },
  {
    id: 21,
    name: "판드라이드",
    nameAbbreviation: "ㅍㄷㄹㅇㄷ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 22,
    name: "크루마",
    nameAbbreviation: "ㅋㄹㅁ",
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
  },
  {
    id: 23,
    name: "템페스트",
    nameAbbreviation: "ㅌㅍㅅㅌ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 24,
    name: "카탄",
    nameAbbreviation: "ㅋㅌ",
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
  },
  {
    id: 25,
    name: "코어수스켑터",
    nameAbbreviation: "ㅋㅇㅅㅅㅋㅌ",
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
  },
  {
    id: 26,
    name: "티미트리스",
    nameAbbreviation: "ㅌㅁㅌㄹㅅ",
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
  },
  {
    id: 27,
    name: "스탄",
    nameAbbreviation: "ㅅㅌ",
    genTime: null,
    time: 7,
    mungCount: 0,
    memo: "",
  },
  {
    id: 28,
    name: "메두사",
    nameAbbreviation: "ㅁㄷㅅ",
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
  },
  {
    id: 29,
    name: "블랙릴리",
    nameAbbreviation: "ㅂㄹㄹㄹ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 30,
    name: "베히모스",
    nameAbbreviation: "ㅂㅎㅁㅅ",
    genTime: null,
    time: 9,
    mungCount: 0,
    memo: "",
  },
  {
    id: 31,
    name: "드래곤비스트",
    nameAbbreviation: "ㄷㄹㄱㅂㅅㅌ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 32,
    name: "가레스",
    nameAbbreviation: "ㄱㄹㅅ",
    genTime: null,
    time: 9,
    mungCount: 0,
    memo: "",
  },
  {
    id: 33,
    name: "사무엘",
    nameAbbreviation: "ㅅㅁㅇ",
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
  },
  {
    id: 34,
    name: "망각의거울",
    nameAbbreviation: "ㅁㄱㅇㄱㅇ",
    genTime: null,
    time: 11,
    mungCount: 0,
    memo: "",
  },
  {
    id: 35,
    name: "히실로메",
    nameAbbreviation: "ㅎㅅㄹㅁ",
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
  },
  {
    id: 36,
    name: "란도르",
    nameAbbreviation: "ㄹㄷㄹ",
    genTime: null,
    time: 9,
    mungCount: 0,
    memo: "",
  },
];
export default boss;
