const boss = [
  {
    id: 1,
    name: "탈킨",
    nameAbbreviation: ["ㅌㅋ"],
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/1",
  },
  {
    id: 2,
    name: "펠리스",
    nameAbbreviation: ["ㅍㄽ", "ㅍㄹㅅ"],
    genTime: null,
    time: 3,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/15",
  },
  {
    id: 3,
    name: "판나로드",
    nameAbbreviation: ["ㅍㄴㄹㄷ"],
    genTime: null,
    time: 5,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/31",
  },
  {
    id: 4,
    name: "브래카",
    nameAbbreviation: ["ㅂㄹㅋ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/30",
  },
  {
    id: 5,
    name: "바실라",
    nameAbbreviation: ["ㅂㅅㄹ", "ㅄㄹ"],
    genTime: null,
    time: 4,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/11",
  },
  {
    id: 6,
    name: "엔쿠라",
    nameAbbreviation: ["ㅇㅋㄹ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/17",
  },
  {
    id: 7,
    name: "체르투바",
    nameAbbreviation: ["ㅊㄾㅂ", "ㅊㄹㅌㅂ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/10",
  },
  {
    id: 8,
    name: "마투라",
    nameAbbreviation: ["ㅁㅌㄹ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/29",
  },
  {
    id: 9,
    name: "트롬바",
    nameAbbreviation: ["ㅌㄼ", "ㅌㄹㅂ"],
    genTime: null,
    time: 7,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/34",
  },
  {
    id: 10,
    name: "사르카",
    nameAbbreviation: ["ㅅㄹㅋ"],
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/24",
  },
  {
    id: 11,
    name: "오크",
    nameAbbreviation: ["ㅇㅋ"],
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/21",
  },
  {
    id: 12,
    name: "셀루",
    nameAbbreviation: ["ㅅㄹ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/2",
  },
  {
    id: 13,
    name: "발보",
    nameAbbreviation: ["ㅂㅂ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/3",
  },
  {
    id: 14,
    name: "티미니엘",
    nameAbbreviation: ["ㅌㅁㄴㅇ"],
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/4",
  },
  {
    id: 15,
    name: "레피로",
    nameAbbreviation: ["ㄿㄹ", "ㄹㅍㄹ"],
    genTime: null,
    time: 7,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/5",
  },
  {
    id: 16,
    name: "코룬",
    nameAbbreviation: ["ㅋㄹ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/8",
  },
  {
    id: 17,
    name: "켈소스",
    nameAbbreviation: ["ㅋㅅㅅ"],
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/12",
  },
  {
    id: 18,
    name: "사반",
    nameAbbreviation: ["ㅅㅂ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/13",
  },
  {
    id: 19,
    name: "여왕개미",
    nameAbbreviation: ["ㅇㅇㄱㅁ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/14",
  },
  {
    id: 20,
    name: "탈라킨",
    nameAbbreviation: ["ㅌㄹㅋ"],
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/16",
  },
  {
    id: 21,
    name: "판드라이드",
    nameAbbreviation: ["ㅍㄷㄹㅇㄷ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/18",
  },
  {
    id: 22,
    name: "크루마",
    nameAbbreviation: ["ㅋㄹㅁ", "ㅋㄻ"],
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/19",
  },
  {
    id: 23,
    name: "템페스트",
    nameAbbreviation: ["ㅌㅍㅅㅌ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/20",
  },
  {
    id: 24,
    name: "카탄",
    nameAbbreviation: ["ㅋㅌ"],
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/22",
  },
  {
    id: 25,
    name: "코어수스켑터",
    nameAbbreviation: ["코어", "ㅋㅇ", "ㅋㅇㅅㅅㅋㅌ"],
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/23",
  },
  {
    id: 26,
    name: "티미트리스",
    nameAbbreviation: ["ㅌㅁㅌㄽ", "ㅌㅁㅌㄹㅅ"],
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/25",
  },
  {
    id: 27,
    name: "스탄",
    nameAbbreviation: ["ㅅㅌ"],
    genTime: null,
    time: 7,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/26",
  },
  {
    id: 28,
    name: "메두사",
    nameAbbreviation: ["ㅁㄷㅅ"],
    genTime: null,
    time: 10,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/27",
  },
  {
    id: 29,
    name: "블랙릴리",
    nameAbbreviation: ["ㅂㄹㄹㄹ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/28",
  },
  {
    id: 30,
    name: "베히모스",
    nameAbbreviation: ["ㅂㅎㅁㅅ"],
    genTime: null,
    time: 9,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/32",
  },
  {
    id: 31,
    name: "드래곤비스트",
    nameAbbreviation: ["드비", "ㄷㅂ", "ㄷㄹㄱㅂㅅㅌ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/33",
  },
  {
    id: 32,
    name: "가레스",
    nameAbbreviation: ["ㄱㄽ", "ㄱㄹㅅ"],
    genTime: null,
    time: 9,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/35",
  },
  {
    id: 33,
    name: "사무엘",
    nameAbbreviation: ["ㅅㅁㅇ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/36",
  },
  {
    id: 34,
    name: "망각의거울",
    nameAbbreviation: ["ㅁㄱ", "망각", "ㅁㄱㅇㄱㅇ"],
    genTime: null,
    time: 11,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/43",
  },
  {
    id: 35,
    name: "히실로메",
    nameAbbreviation: ["ㅎㅅㄻ", "ㅎㅅㄹㅁ"],
    genTime: null,
    time: 6,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/44",
  },
  {
    id: 36,
    name: "란도르",
    nameAbbreviation: ["ㄹㄷㄹ"],
    genTime: null,
    time: 9,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/45",
  },
  {
    id: 37,
    name: "카브리오",
    nameAbbreviation: ["ㅋㅂㄹㅇ"],
    genTime: null,
    time: 12,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/152",
  },
  {
    id: 38,
    name: "글라키",
    nameAbbreviation: ["ㄱㄹㅋ"],
    genTime: null,
    time: 8,
    mungCount: 0,
    memo: "",
    audioUrl: "http://timebot.co.kr/sound/lin2m/46",
  },
];
export default boss;
